# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e2fbf41df2da460692dd7db4ccad32a5d15d2c6cc2441b70a01a32b2f7c6bb2a2ff3b9ba0d787dd758865e82ee8c761873dfac68c3c321a3f155fddcb9ea8cb6

test:
  secret_key_base: 7840d3e9b36e1486a56fbb4d6f79ca069cff6b596f1947a1a1e146b62a8d156fd57ce394c30e1cafbfb786c75cc9df370a0e97b4a14c39aed6eab8831352b378

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
